### ISSUE TITLE
DEPRECATION: project.nodeModulesPath

### ISSUE THREAD

**Issue by richipargo** [offirgolan/ember-burger-menu#101]
Deprectaion warning 
An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/home/richipargo/Projects/Eucledian/eucledian-web/node_modules/ember-burger-menu/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)

**Comment by offirgolan** [comment]
Should be resolved in `v3.0.2`
