### ISSUE TITLE
Swipe Events - e.touches[0] is undefined

### ISSUE THREAD

**Issue by timjcook** [offirgolan/ember-burger-menu#12]
Hi guys,

I'm having an issue where my swipe events aren't being handled correctly.
https://github.com/offirgolan/ember-burger-menu/blob/master/addon/mixins/swipe-support.js#L19

Seems as though `e.touches` has no elements, `Cannot read property '0' of undefined`

I've basically copy/pasted the demo menu from the docs and I'm still getting the issue. Any ideas?
I am on `1.0.0`.

Thanks for your work on this project, looks 👌

**Comment by offirgolan** [comment]
@timjcook can you give me some more env info?

- Browser version
- Device version
- Ember version
- OS

**Comment by timjcook** [comment]
@offirgolan sure thing
- I've definitely got the issue in Chrome (55.0.2883.95) and FF (50.1.0)
- Ember 2.7
- Mac OS Sierra (10.12)

**Comment by offirgolan** [comment]
@timjcook fixed in `v1.0.1` 😸

**Comment by timjcook** [comment]
@offirgolan legend! thanks :v:

**Comment by offirgolan** [comment]
Haha np! Thanks for bringing this to my attention.
