### ISSUE TITLE
Octane

### ISSUE THREAD

**Issue by aalimovs** [offirgolan/ember-burger-menu#121]
Is anyone using `ember-burger-menu` with Octane?

I can't seem to toggle the burger `open` state from outside.

```hbs
<button onClick={{action (mut this.isOpen) (not this.isOpen)}}>Toggle</button>

{{#burger-menu open=this.isOpen as |burger|}}
    {{#burger.outlet}}
        hello world
    {{/burger.outlet}}
{{/burger-menu}}
```

`burger-menu` seems not to react to `this.isOpen` at all. If I set it initially to true, it does render opened, but as I change `this.isOpen`, the menu never appears again.

**Comment by lifeart** [comment]
@aalimovs `<button onclick={{action (mut this.isOpen) (not this.isOpen)}}>Toggle</button>`

**Comment by aalimovs** [comment]
@lifeart no luck. I can see `this.isOpen` is being mutated on every toggle when I print `{{this.isOpen}}` in the template, but `burger-menu` doesn't open

**Comment by knownasilya** [comment]
The issue is async observers. This is setup https://github.com/offirgolan/ember-burger-menu/blob/master/addon/components/burger-menu.js#L78 before the menu open event is finished and closes the menu with the `onClick` handler.
