### ISSUE TITLE
Ember htmlSafe is now part of @ember/template

### ISSUE THREAD

**Issue by kevintraver** [offirgolan/ember-burger-menu#175]
For newer version of Ember, `htmlSafe` is now part of `@ember/template` instead of `@ember/string`

https://github.com/adopted-ember-addons/ember-burger-menu/blob/cc934f00f6e02d4679ada8e0c6404bf84be98f87/addon/utils/css-stringify.js#L2

**Comment by rnosek** [comment]
Looks like dasherize is still apart of '@ember/string'

` import { htmlSafe } from '@ember/template'; 
 import { dasherize } from '@ember/string'; `
