### ISSUE TITLE
Add link from demo to Github

### ISSUE THREAD

**Issue by sandstrom** [offirgolan/ember-burger-menu#2]
Awesome component! ⛵️ 

For simplicity you could add a link from the demo page to the [Github page](https://github.com/offirgolan/ember-burger-menu). I'm sure 95% can find it through a Google-search, but anyway :)

**Comment by offirgolan** [comment]
Hi @sandstrom! Glad you like the addon 😸.

There is already a link in the demo site. Its the first link when you open up the menu but maybe thats too hidden? If so, I'll add it in another location!

**Comment by sandstrom** [comment]
Ah, I see! 

Obviously too hidden for me 😉  but I'll let you decide! (this is a minor thing to begin with)
