### ISSUE TITLE
There is no css style included in the package

### ISSUE THREAD

**Issue by zardaloop** [offirgolan/ember-burger-menu#23]
Hi Guys, 
I followed the tutorial to use the code from here [https://github.com/offirgolan/ember-burger-menu#usage](url) and then replaced 
`<a class="icon-menu" {{action burger.state.actions.toggle}}></a>`
with 
`<button {{action burger.state.actions.toggle}}>button</button>`
since I don't have icon-menu class and without replacing it into button I can' see anything. 
could someone please advise me what css classes and styles I need to add to be able to see the menu something like the one from here [https://offirgolan.github.io/ember-burger-menu/](url)
Because what I see now has absolutely no style at all and copying all the styles from think link [https://github.com/offirgolan/ember-burger-menu/blob/master/tests/dummy/app/styles/app.scss](url) totally mess up the whole application.

I really like the package, you guys did a great job but I am really straggling using it.

**Comment by offirgolan** [comment]
@zardaloop I'm sorry you're facing so many issues. This library only comes with barebone CSS just to get you up and running. All styles beyond that is up to you. Im sorry for the confusion as well from the readme, I've updated it to just include plain buttons with no icon classes as this library doesnt come with those either. 

You are welcome to grab the main styles for the demo [here](https://github.com/offirgolan/ember-burger-menu/blob/master/tests/dummy/app/styles/app.scss#L45-L123). You might have to alter it a bit to fit your template / needs.

**Comment by zardaloop** [comment]
@offirgolan  perfect that did the job. I added some more styles from the css but it works fine now :) thanks.  of course I also installed ember-font-awesome as well to make it more like what you have in your demo page :) Thanks.

**Comment by offirgolan** [comment]
@zardaloop thats great to hear! Glad everything is working fine for you now 😄
