### ISSUE TITLE
Can ember-burger-menu stays open?

### ISSUE THREAD

**Issue by aleyrizvi** [offirgolan/ember-burger-menu#24]
Hi,
It is not an issue but just a question.

My requirements are to keep burger-menu open until the viewport hits sm (I am using bootstrap grid or flexi if that matters)

Is there any class which I can toggle to keep it open and burger-icon hidden and only close burger menu based on criteria?

**Comment by offirgolan** [comment]
Yeah it should support it out of the box. Just make sure to set the following options:

```hbs
{{burger-menu open=true dismissOnClick=false dismissOnEsc=false}}
```

Then you can just use the burgerMenu service ([see README](https://github.com/offirgolan/ember-burger-menu#via-service)) to close the menu once your viewport reaches a specific size. You can also change the width of your menu via the service as your viewport width changes.

**Comment by offirgolan** [comment]
You can now used the `locked` option.

```hbs
{{burger-menu open=true locked=true}}
```

**Comment by aleyrizvi** [comment]
Excellent!

Thank you for the udpate. 

I can now test and use it without worrying :)
