### ISSUE TITLE
Animation type that doesn't cover or push contents off screen

### ISSUE THREAD

**Issue by devinholloway** [offirgolan/ember-burger-menu#61]
It appears that each of the animation types either cover up the screen contents (slide) or push the contents off the screen (reveal). It would be great to have the ability for the content area to use up 100% of available space when the menu is opened and closed.

**Comment by offirgolan** [comment]
@devinholloway done 😄 

See demo: https://offirgolan.github.io/ember-burger-menu/#/?animation=slide-shrink

**Comment by devinholloway** [comment]
Perfect!
