### ISSUE TITLE
JQuery warnings when swiping

### ISSUE THREAD

**Issue by Moxide** [offirgolan/ember-burger-menu#69]
Hello,
In Chromium, when I start to swipe the menu (and during the swiping), hundreds of warning are thrown in the console :
```
jquery.js:5445 Unable to preventDefault inside passive event listener due to target being treated as 
passive. See [https://www.chromestatus.com/features/5093566007214080](https://www.chromestatus.com/features/5093566007214080)
preventDefault	@	jquery.js:5445
touchMove	@	swipe-support.js:57
trigger	@	ember.debug.js:42833
...
```
As it is stated in [chromestatus](https://www.chromestatus.com/features/5093566007214080), `preventDefault` is no longer necessary and if a remove this call from the `touchMove` event in `swipe-support.js`, the warnings are gone ;-)

**Comment by offirgolan** [comment]
@Moxide thanks for bringing this to my attention. I'll look into it sometime this week/weekend.
