### ISSUE TITLE
love the look and function of Ember Burger Menu!

### ISSUE THREAD

**Issue by markmm9** [offirgolan/ember-burger-menu#75]
but...I am a designer more than a developer. I know enough  be dangerous tho, like dropping in css into my WP site or editing some html in spots.

but my question for offirgolan is, is there a layman's/noob guide for how a rank beginner (that would be me) would install this code on their WP site? (please)

Thanks for any help you can give. 
Mark

**Comment by offirgolan** [comment]
@markmm9 thank you for the kind words 😍. Unfortunately, this library is for EmberJS only and does not support WP. I was able to find a WP plugin [here](https://wordpress.org/plugins/responsive-menu/) that has similar functionalities as this repo but I'm not sure if thats what you're looking for. 

All the CSS from this repo can be found here:

- [Default Styles](https://github.com/offirgolan/ember-burger-menu/tree/master/addon/styles)
- [Demo Styles](https://github.com/offirgolan/ember-burger-menu/blob/master/tests/dummy/app/styles/app.scss)

I hope that helps!

**Comment by markmm9** [comment]
ah, ok, thanks Offir!
On May 7, 2017, at 7:04 PM, Offir Golan <notifications@github.com> wrote:

@markmm9 <https://github.com/markmm9> thank you for the kind words 😍. Unfortunately, this library is for EmberJS only and does not support WP. I was able to find a WP plugin here <https://wordpress.org/plugins/responsive-menu/> that has similar functionalities as this repo but I'm not sure if thats what you're looking for.

All the CSS from this repo can be found here:

Default Styles <https://github.com/offirgolan/ember-burger-menu/tree/master/addon/styles>
Demo Styles <https://github.com/offirgolan/ember-burger-menu/blob/master/tests/dummy/app/styles/app.scss>
I hope that helps!
