### ISSUE TITLE
Documentation doesn't explain enough to get started

### ISSUE THREAD

**Issue by Hucxley** [offirgolan/ember-burger-menu#76]
I'm getting an assertion error: "Assertion Failed: A helper named "burger.menu" could not be found".

This looks great, with plenty of options, but nothing that really explains how to use them.  I don't know how to set options for the menu, even though your demo site has tons of options that you've already created and set up.

Is there any way to get some better documentation for the rest of it like you did for animations?

**Comment by offirgolan** [comment]
@Hucxley I'm not sure what you mean. The Readme has all the options for each components laid out and explained. Is there something specific you do not understand? 

As for your error, can you post a snippet of your code? Maybe I can be of better help then 😄

**Comment by emanuelschmitt** [comment]
I have the same problem here, I installed the plugin via ember-cli and I can't import the sass files into my style.scss and also the helper is not found. I check node_modules and the folder for burger menu is available. It seems that burger menu is not added to the build path... :/

**Comment by pusle** [comment]
I have the same problem as @emanuelschmitt regarding the `@import 'ember-burger-menu` after doing an `ember install ember-burger-menu` on ember 2.10. All scss files are installed in the _node_modules/ember-burger-menu/app/styles_, but importing them in the ember app is not working. I feel there is something I'm doing wrong, so perhaps something is missing from the docs?

**Comment by emanuelschmitt** [comment]
You have to reload your dev server. Close the ember server process and restart it again, then it will work!

**Comment by pusle** [comment]
@emanuelschmitt Sorry for wasting your time. I can not believe I made that mistake!
