### ISSUE TITLE
this.removeEventListener is not a function

### ISSUE THREAD

**Issue by dephora** [offirgolan/ember-burger-menu#78]
First off, really appreciate the addon.

I'm intermittently receiving the error in the title (and picture below). It can be duplicated 100% of the time if ember-scrollable is installed (haven't looked into the relation there). The addons don't have to be in the same route for the issue to occur.

As a temp fix I changed lines 69-77 in burger-menu.js as I don't require `dismissOnClick` or `dismissOnEsc`.

```javascript
_teardownEvents() {
    if (this.get('dismissOnClick')) {
      this.removeEventListener(this.$(), 'click', this.onClick);
      this.removeEventListener(this.$(), 'touchstart', this.onClick);
    }

    if (this.get('dismissOnEsc')) {
      this.removeEventListener(document, 'keyup', this.onKeyup);
    }
  },
```

![image](https://cloud.githubusercontent.com/assets/5777341/25838193/e87bf24a-345f-11e7-9106-b683545169e3.png)

My project (burger menu in the index route, ember-scrollable in the scrollable route.
https://github.com/dephora/ember-burger-menu-test

I've only tested this with 2.13

**Comment by offirgolan** [comment]
Hi @dephora thank you creating this issue. I believe that this issue has something to do with a dependency collision of `ember-lifeline`. 

`ember-scrollable` requires `ember-lifeline` **v1.0.0** where as this addon require **v1.0.4** which has the `removeEventListener` function. 

Are you using yarn? If not, please consider switching to it as it should solve this issue.

**Comment by dephora** [comment]
@offirgolan 

I created a new project with yarn as the default, installed both addons. yarn.lock had both 1.0.0 and 1.0.4 of ember-lifeline. Same error.

Created a fork of ember-scrollable, changed the lifeline dep to 1.0.4, used the fork instead and updated with yarn install. This removed the 1.0.0 lifeline and all seems to be working fine.

What would be the best course of action from here?

**Comment by offirgolan** [comment]
@dephora I made a new patch release on ember-scrollable with the fix. Please update to `v0.4.6` 😄

**Comment by dephora** [comment]
@offirgolan Perfect, everything appears to be working now. Really appreciate the quick responses.

**Comment by offirgolan** [comment]
Sweet! No problem at all. This has been an issue for a couple of other people and I had no idea why it was happening since I couldnt reproduce it. Thanks for creating the detailed issue 😄.
