### ISSUE TITLE
Access burger menu context from ember route?

### ISSUE THREAD

**Issue by dbollinger** [offirgolan/ember-burger-menu#85]
I have a use case where I want to conditionally trigger opening and closing the menu during route transitions.  Additionally, it would be nice to be able to send actions from components in nested routes up to the application to trigger opening and closing the burger menu.

From what I can tell, this seems like it is out of the scope of this add-on.  Is this a correct assumption?

**Comment by offirgolan** [comment]
@dbollinger I would create a `burger-menu` service that has an `open` property. Once created, you can pass it to the component like so `{{burger-menu open=burgerMenuService.open}}`.

Now you can inject your service anywhere in your app and toggle the open state of the menu.

**Comment by dbollinger** [comment]
That makes perfect sense.  Thank you! 

Did not think to pass the property into the component like that.

**Comment by offirgolan** [comment]
No problem at all 😄
