### ISSUE TITLE
How to lock menu open and continue to view rest of app normally?

### ISSUE THREAD

**Issue by maxwerr** [offirgolan/ember-burger-menu#89]
I'm using the menu `locked` `open`, `translucentOverlay=false` on large enough device sizes, but the outlet for the rest of the app is translated/obfuscated and not very usable... Is there any way to handle this using the burger menu options? Thanks!

**Comment by offirgolan** [comment]
@maxwerr if you intend to have to menu open, I would use the `squeeze` animation as it also shrinks the outlet to accommodate for the menu.

**Comment by maxwerr** [comment]
ohhhh 👀 perfect. I missed that one on the demo page. thanks for the lightning response!

**Comment by offirgolan** [comment]
No problem at all! 😄
