### ISSUE TITLE
Adding LESS files

### ISSUE THREAD

**Issue by mrhanky17** [offirgolan/ember-burger-menu#90]
Hi,
would it be possible to also have LESS stylesheets? I don't know (right now) how much work this would be, but I think having less available would be neat for users using Semantic UI or other LESS based frameworks.

Any thougts on this?

**Comment by offirgolan** [comment]
@mrhanky17 I dont think that is something that will be supported in the near future. You are welcome to use v2.x which doesnt require your app to use sass (it uses sass internally but serves up a compiled css file to your application).
