### ISSUE TITLE
Is there documentation for how to set up multiple menus?

### ISSUE THREAD

**Issue by ptingiris** [offirgolan/ember-burger-menu#92]
First -- great plugin!  Sorry if I missed something, but I can't find any documentation for how to set up multiple menus like the ones shown on the demo page.  So far, everything else works like a charm!

**Comment by offirgolan** [comment]
@ptingiris the demo is not a true representation of how to setup multiple menus (it's mostly just for show). The only way it would actually work is if you nested them.

```hbs
{{#burger-menu as |bm|}}
  {{#bm.outlet}}
    {{#burger-menu}} ... {{/burger-menu}}
  {{/bm.outlet}}
{{/burger-menu}}
```

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
