### ISSUE TITLE
Ember 2.15 Actions Not Found

### ISSUE THREAD

**Issue by donaldwasserman** [offirgolan/ember-burger-menu#94]
I just upgraded my app to ember 2.15. The various `burger.state.actions.<toggle | open | close>` result in an undefined error: 

`Error: Assertion Failed: You specified a quoteless path, `toggle`, to the {{action}} helper which did not resolve to an action name (a string). Perhaps you meant to use a quoted actionName? (e.g. {{action "toggle"}}).`

Reverting ember-source, ember-cli back to 2.14 seems to resolve this issue.

After trying to put together a pull request to fix this issue, i can't replicate it in the Demo app of ember-burger-menu, so now I'm not sure if this is a me problem or something else.

**Comment by offirgolan** [comment]
@donaldwasserman any chance you can recreate this in a dummy app?

**Comment by donaldwasserman** [comment]
Hey - Sorry about this. For some reason this is happening my app, but i can't recreate in isolation. Apologies.

**Comment by donaldwasserman** [comment]
For the google:

I put one of the state actions inside a partial inside the `{{burger.outlet}}` [example](https://github.com/donaldwasserman/burger-demo/blob/master/app/templates/application.hbs#L31 )

I couldn't find any release notes or documentation about it, but it doesn't appear you can access the component context like that

**Comment by offirgolan** [comment]
@donaldwasserman thanks for the follow up! I'm glad you were able to find the root cause for the issue. Hopefully it gets fixed in a patch release soon 😄
