### ISSUE TITLE
Problems with setup

### ISSUE THREAD

**Issue by eduardo-hyodo** [offirgolan/ember-burger-menu#96]
Hey guys,

Was having trouble making this work in my project, so I decided to create a brand new 2.14 project to see if I can get it to work... and I still cannot.

What step am I missing?

I basically did:
`ember new dummy `
`cd dummy`
`ember install ember-burger-menu`
`ember g template index `

then I went into application template and pasted the code from the documentations (just changed the links to index):
```
{{#burger-menu as |burger|}}
  {{#burger.menu itemTagName="li" as |menu|}}
    <a {{action burger.state.actions.close}} class="icon-close"></a>

    <ul>
      {{#menu.item}}
        {{link-to 'index' 'index'}}
      {{/menu.item}}

      {{#menu.item}}
        {{link-to 'index' 'index'}}
      {{/menu.item}}

      {{#menu.item}}
        {{link-to 'index' 'index'}}
      {{/menu.item}}
    </ul>
  {{/burger.menu}}

  {{#burger.outlet}}
    <a class="icon-menu" {{action burger.state.actions.toggle}}></a>
    {{outlet}}
  {{/burger.outlet}}
{{/burger-menu}}
```
and went into index and pasted

`Please show up hi from index`

when I navigate to localhost:4200 I see a blank page with my sentence; 
Bit confused on what am I doing wrong... I really would love to get this to work.

No error on console when I inspect

Thank you

**Comment by Mithrilhall** [comment]
@eduardo-hyodo

I had a similar experience. I ended up grabbing the css used in the demo to make it show and just used what I needed.

[CSS](https://offirgolan.github.io/ember-burger-menu/assets/dummy-62e707c579556b21451abadaed88dafb.css)

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
