### ISSUE TITLE
Ember Lifeline No Longer Supports jQuery selectors

### ISSUE THREAD

**Issue by donaldwasserman** [offirgolan/ember-burger-menu#97]
I just updated ember-light-table to 1.12.2 (from 1.8.6), which bumped `ember-lifeline.`

Ember-Lifeline stops supporting jquery selectors here https://github.com/rwjblue/ember-lifeline/blob/master/addon/mixins/dom.js, resulting in: `Called addEventListener with selector not found in DOM [Object: Object]`

PR forthcoming.

**Comment by lypborges** [comment]
Same error here.
